version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./uploads:/app/uploads
    expose:
      - "8080"
    depends_on:
      - database
    networks:
      - app-network

  database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BUILD_DIR=dist
        - VITE_API_URL=/api
    ports:
      - "81:81"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - certbot-letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
  certbot-letsencrypt:
  certbot-www: