ktor:
  application:
    modules:
      - com.inRussian.ApplicationKt.module
  deployment:
    port: 8080
    host: localhost
  development: true
admin:
  email: "admin@example.com"
  password: "changeMeToAStrongPassword"
jwt:
  domain: "http://localhost:8080/"
  audience: "jwt-audience"
  realm: "ktor sample app"
postgres:
  url: "jdbc:postgresql://localhost:5432/InRussianBackup"
  user: postgres
  password: postgres
  maximumPoolSize: 10
  minimumIdle: 2
  connectionTimeout: 30000

