openapi: 3.0.3
info:
  title: Learning App API
  version: 0.1.0
servers:
  - url: https://api.example.com
paths:


  /courses/{courseId}/progress:
    get:
      summary: Get progress for current user
      parameters:
        - in: path
          name: courseId
          required: true
          schema: { type: string, format: uuid }
      responses:
        '200': { description: OK }
  /sections/{sectionId}/progress:
    get:
      summary: Get section progress for current user
      parameters:
        - in: path
          name: sectionId
          required: true
          schema: { type: string, format: uuid }
      responses:
        '200': { description: OK }
  /sections/{sectionId}/seed-queue:
    post:
      summary: Seed queue for a section by theme batches
      parameters:
        - in: path
          name: sectionId
          required: true
          schema: { type: string, format: uuid }
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                themesToSeed:
                  type: integer
                  default: 1
      responses:
        '200': { description: Seeded }
  /sections/{sectionId}/tasks/next:
    get:
      summary: Get the next task for user
      parameters:
        - in: path
          name: sectionId
          required: true
          schema: { type: string, format: uuid }
        - in: query
          name: scope
          schema:
            type: string
            enum: [section, course]
            default: section
        - in: query
          name: mix
          schema:
            type: boolean
            default: true
      responses:
        '200': { description: OK }
        '204': { description: No task available }
  /attempts:
    post:
      summary: Submit task attempt (idempotent)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [attemptId, taskId, tries, timeSpentMs, solved]
              properties:
                attemptId: { type: string, format: uuid }
                taskId: { type: string, format: uuid }
                tries: { type: integer, minimum: 1 }
                timeSpentMs: { type: integer, minimum: 0 }
                solved: { type: boolean }
                payload: { type: object, additionalProperties: true }
      responses:
        '200': { description: OK }
        '409': { description: Conflicting idempotency key }
  /me/badges:
    get:
      summary: List badges for current user
      responses:
        '200': { description: OK }
  /badges:
    get:
      summary: List all badges
      responses:
        '200': { description: OK }
components: {}